### ISSUE TITLE
PCE autofire entry missing

### ISSUE THREAD

**Issue by ghost** [AmatCoder/mednaffe#141] opened 2022-01-26 17:35 UTC
PCE/TG16 auto fire entry missing (retail tg16 have autofire) some games need it

**Comment by Eggo-dotcom** [comment] 2022-01-26 17:37
seems rapid fire is only missing on this system (this system has software written for use with autofire)

current walk around is map via mednafen

**Comment by AmatCoder** [comment] 2022-01-28 20:05
Confirmed, rapid input is missing on **pce** and **pce_fast** modules.
Thanks for reporting.

**Comment by Eggo-dotcom** [comment] 2022-01-29 00:57
Thanks for reading.

**Comment by Eggo-dotcom** [comment] 2022-01-29 01:31
i see you added already. anywhere to download devbuilds?

**Comment by AmatCoder** [comment] 2022-01-30 11:08
I uploaded last windows build here: https://ufile.io/day5i6pe

**Comment by Eggo-dotcom** [comment] 2022-01-30 13:01
> I uploaded last windows build here: https://ufile.io/day5i6pe

Thank you!!

**Comment by Eggo-dotcom** [comment] 2022-01-30 14:20
Works great!

**Comment by Eggo-dotcom** [comment] 2022-02-06 02:24
maybe release this build for all to see? these updates were a must for anyone with boxart and or using pce

**Comment by Shinobi-1987** [comment] 2022-02-20 01:23
Ghost is me, new account,still using this build, only thing i see it really needing is the ability to specify path for mednafen due to a bug i noticed whe placing a shortcut on a windows 10 desktop if stored on a secondary hdd.

**Comment by Shinobi-1987** [comment] 2022-03-20 02:27
Maybe release this fix build?

**Comment by Shinobi-1987** [comment] 2022-04-23 04:31
> > I uploaded last windows build here: https://ufile.io/day5i6pe
> 
> Thank you!!
> 
> will test today

Works amazing but download link expired for others

**Comment by AmatCoder** [comment] 2024-04-14 08:34
Fixed with version [0.9.3](https://github.com/AmatCoder/mednaffe/releases/tag/0.9.3).

**Closed by AmatCoder** 2024-04-14 08:34 UTC
Labels: bug
