### ISSUE TITLE
Add a new option Only ZIPs and supported extensions

### ISSUE THREAD

**Issue by cpcbegin** [AmatCoder/mednaffe#82] opened 2018-05-01 18:48 UTC
If you have a folder with several type of files, now you can see all the files, only ZIPs or only supported extensions.
Maybe a good idea add a new option to see only ZIPs and supported extensions to avoid other files like png, jpg, etc...

**Comment by AmatCoder** [comment] 2018-05-04 06:37
Closing as duplicate of #54 

It will not filter automatically supported extensions but will allow the user decide which extensions to include.

**Closed by AmatCoder** 2018-05-04 06:37 UTC
Labels: duplicate
