### ISSUE TITLE
art too high at start images attached to show

### ISSUE THREAD

**Issue by Eggo-dotcom** [AmatCoder/mednaffe#140] opened 2022-01-26 13:42 UTC
So front end is great, However one small glitch im noticing with snaps/artwork, on initial open everything moves up to high, happens with fresh installs on any windows 10 machine. attaching two pics, bad is what happens and proper is expected behavior. Also Ide like to saty im not complaining just reporting what I notice in case you want to know. im already happy with my setup.
![bad](https://user-images.githubusercontent.com/84027465/151173516-2f5dbc95-680d-4eb9-bffc-27cae521ac6b.JPG)
![proper](https://user-images.githubusercontent.com/84027465/151173518-ebf69d3c-381d-4c0d-81ce-fe133fd7a9aa.JPG)

**Comment by Eggo-dotcom** [comment] 2022-01-27 12:34
so more info the following is from config


[GUI]
Dirs=C:\\Users\\James.UNIROPE\\Desktop\\A8\\INCOMMING\\no-tg16,false,true,*.*,C:\\Users\\James.UNIROPE\\Desktop\\A8\\INCOMMING\\mednafen\\snaps,C:\\Users\\James.UNIROPE\\Desktop\\A8\\INCOMMING\\mednafen\\artwork,972,972;



Now if i have save window size position enabled the second 972 randomly changes, if i turn save size position off and edit to 972,927 its always ok.

**Comment by AmatCoder** [comment] 2022-01-28 20:22
I was able to reproduce this.

It seems to be a race condition between GtkPaned and GtkWindow.
When mednaffe is launched, GTK set positions of paned then resize window (it should be the other way around).

**Comment by Eggo-dotcom** [comment] 2022-01-29 00:58
> I was able to reproduce this.
> 
> It seems to be a race condition between GtkPaned and GtkWindow. When mednaffe is launched, GTK set positions of paned then resize window (it should be the other way around).

my current temp fix is running with cfg as read only, rror on exit but runs flawless

**Comment by AmatCoder** [comment] 2022-01-30 10:47
Fixed with commit 77c53bf

This race condition happened when state of GtkWindow was maximized, because:

> [...] maximization is ultimately handled by the window manager and happens asynchronously to an application request [...]

(From [GTK documentation](https://docs.gtk.org/gtk3/method.Window.is_maximized.html))

**Comment by Eggo-dotcom** [comment] 2022-01-30 13:39
So if I understand correctly when the window was maximized the code vs windows were both computing i guess? Will test your new dev build and report back. Thank you.

**Comment by Eggo-dotcom** [comment] 2022-01-30 14:20
Works good now with the update you shared!!

**Closed** 2022-01-31 15:46 UTC
Labels: bug
