### ISSUE TITLE
Mednaffe won't accept up/right D-Pad inputs in controller setup

### ISSUE THREAD

**Issue by SatoXa** [AmatCoder/mednaffe#79] opened 2018-04-25 16:51 UTC
Using Mednaffe 0.8.7, trying to setup my controller for the PlayStation core. I'm using a DualShock 4 with DS4Windows, however this issue also occurs if I turn DS4Win off and use the DS4's native DirectInput. 

When configuring my inputs, I can configure up/down/left/right just fine:

![image](https://user-images.githubusercontent.com/9293417/39260256-db01e64a-48b0-11e8-8395-e684602fced4.png)

However, if I change tabs to 'Port 2', close the input config window, or do _essentially anything else_ that involves leaving the 'Port 1' input config screen, the config changes itself to this:

![image](https://user-images.githubusercontent.com/9293417/39260315-fcfbdaf8-48b0-11e8-8168-c62a9514830a.png)

Sadly, playing games with only two directions available can be a _tad_ difficult ;P. Any idea what could be causing this?

**Comment by AmatCoder** [comment] 2018-04-26 20:26
Confirmed.
This is a (stupid) bug and regression because works fine with 0.8.6.
Thanks very much for report it.

**Comment by AmatCoder** [comment] 2018-04-27 18:45
Please, can you test this [executable](https://sites.google.com/site/amatcoder/mednaffe/downloads/mednaffe_test.zip?attredirects=0&d=1) to confirm that this issue has been fixed?

**Comment by SatoXa** [comment] 2018-04-28 14:31
Yep, that fixed it completely. Thanks for the quick update!

**Comment by AmatCoder** [comment] 2018-05-01 18:12
Fixed with 0.8.8 version released.

**Closed by AmatCoder** 2018-05-01 18:12 UTC
Labels: Priority-High, bug
