### ISSUE TITLE
Please support mapping multiple keys to a function and core input key

### ISSUE THREAD

**Issue by leoxxx** [AmatCoder/mednaffe#180] opened 2024-03-24 16:22 UTC
Like this:

```
;Exit
command.exit keyboard 0x0 69 || keyboard 0x0 41

```
I edit cfg or conf, it's O.K.

**Comment by AmatCoder** [comment] 2024-04-14 09:05
Duplicate of issue #132

**Closed by AmatCoder** 2024-04-14 09:05 UTC
