### ISSUE TITLE
mednaffe 0.8.7 and 0.8.8 do not let usr choose a unique filter for games

### ISSUE THREAD

**Issue by CaioVdmm** [AmatCoder/mednaffe#81] opened 2018-05-01 15:58 UTC
these two versions of the front does not let the user choose how to filter the game files, for example by m3u only.

**Comment by AmatCoder** [comment] 2018-05-01 16:53
What do you mean? None of the versions released allows that.

**Comment by CaioVdmm** [comment] 2018-05-02 19:12
was to choose the file extension that you wanted the mednaffe to look for.
sorry for my english

**Comment by CaioVdmm** [comment] 2018-05-02 19:25
an idea is put a custom filter and if this filter is chosen open a window to user write the desire extension

**Comment by AmatCoder** [comment] 2018-05-04 06:26
> Mednaffe let you choose the filter at the time you chose the folder where the games were. if you compile from master and use mednafen 0.9 ... you will see

Mednaffe is being rewritten so master is deprecated.
I am using a branch with only bugfixes for 0.8.x releases and I am developing the new 0.9.0 version here in local.

When it is in a usable condition (it is about 90%) I will upload to master. And, yes, it will have this feature.

**Comment by AmatCoder** [comment] 2018-05-04 06:38
Also closing as duplicate of #54

**Closed by AmatCoder** 2018-05-04 06:38 UTC
Labels: duplicate
